[package]
name = "video_fetch"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
tokio.workspace = true
domains.workspace = true
errors.workspace = true
clap.workspace = true