services:
  meilisearch:
    image: getmeili/meilisearch:v1.15.2
    container_name: meilisearch_container
    ports:
      - "${MEILI_OUTER_PORT}:${MEILI_INNER_PORT}"
    environment:
      MEILI_HTTP_ADDR: "${MEILI_HTTP_ADDR}"
      MEILI_MASTER_KEY: "${MEILI_MASTER_KEY}"
      MEILI_LOG_LEVEL: "${MEILI_LOG_LEVEL}"
      MEILI_ENV: "${MEILI_ENV}"
    volumes:
      - tss-meilisearch:/data.ms
volumes:
  tss-meilisearch:
    driver: local